"""CLI entrypoint for governance engine."""

from __future__ import annotations

import argparse
import json
import logging
import sys
import uuid
from pathlib import Path

from .adapters import MockAdapter, OpenClawAdapter, PcAgentLoopAdapter
from .benchmark import PinchBenchRunConfig, run_pinchbench
from .core.errors import SpecError
from .core.runtime import GovernanceRuntime
from .dashboard_server import serve_dashboard
from .observability.task_manager import TaskRunManager
from .spec.compiler import compile_spec, export_ir_json
from .spec.templates import SUPPORTED_PATTERNS, build_spec_template
from .storage.jsonl import JsonlStore


def main() -> None:
    parser = argparse.ArgumentParser(description="MAS governance engine")
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        help="logging level",
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_compile = sub.add_parser("compile", help="compile CUE/JSON spec into normalized JSON IR")
    p_compile.add_argument("--spec", required=True, help="path to .cue or .json spec")
    p_compile.add_argument("--out", required=True, help="path to output JSON")

    p_validate = sub.add_parser("validate", help="validate spec")
    p_validate.add_argument("--spec", required=True, help="path to .cue or .json spec")

    p_init = sub.add_parser("init-spec", help="generate a starter spec template")
    p_init.add_argument("--id", required=True, help="spec id")
    p_init.add_argument("--name", default="", help="display name (default: same as id)")
    p_init.add_argument("--pattern", required=True, choices=SUPPORTED_PATTERNS)
    p_init.add_argument("--out", required=True, help="output JSON file path")

    p_run = sub.add_parser("run", help="execute a task with given governance spec")
    p_run.add_argument("--spec", required=True, help="path to .cue or .json spec")
    p_run.add_argument("--task-id", default="", help="task id (default autogenerated)")
    p_run.add_argument("--title", required=True, help="task title")
    p_run.add_argument("--input", required=True, dest="input_text", help="task input text")
    p_run.add_argument("--adapter", choices=["mock", "openclaw", "pc-agent-loop"], default="mock")
    p_run.add_argument("--mock-script", default="", help="JSON file: {agent_id: [decision,...]}")
    p_run.add_argument("--openclaw-bin", default="openclaw", help="OpenClaw executable path")
    p_run.add_argument(
        "--openclaw-deliver-mode",
        choices=["auto", "always", "never"],
        default="auto",
        help="whether to append --deliver when invoking OpenClaw",
    )
    p_run.add_argument(
        "--openclaw-project-dir",
        default="",
        help="working directory for OpenClaw CLI execution",
    )
    p_run.add_argument(
        "--pc-agent-root",
        default="third_party/pc-agent-loop",
        help="path to pc-agent-loop root directory",
    )
    p_run.add_argument(
        "--pc-mykey",
        default="",
        help="optional path to mykey.py/mykey.json for pc-agent-loop",
    )
    p_run.add_argument(
        "--pc-llm-no",
        type=int,
        default=-1,
        help="select backend index in pc-agent-loop (default: keep runtime default)",
    )
    p_run.add_argument(
        "--pc-shared-instance",
        action="store_true",
        help="share one pc-agent-loop agent instance for all runtime_ids",
    )
    p_run.add_argument("--trace-out", default="", help="JSONL trace output path")
    p_run.add_argument("--max-steps", type=int, default=0, help="runtime step budget")
    p_run.add_argument("--human-confirm", action="store_true", help="enable interactive HITL callback")

    p_serve = sub.add_parser("serve", help="start dashboard backend (API + event stream)")
    p_serve.add_argument("--host", default="127.0.0.1", help="bind host")
    p_serve.add_argument("--port", type=int, default=8787, help="bind port")
    p_serve.add_argument(
        "--trace-dir",
        default="traces/dashboard",
        help="directory for per-task trace jsonl files",
    )
    p_serve.add_argument(
        "--institutions",
        default="systems/institutions.yaml",
        help="institution registry file",
    )

    p_bench_pinch = sub.add_parser(
        "bench-pinch",
        help="run PinchBench tasks via MAS runtime",
    )
    p_bench_pinch.add_argument(
        "--pinch-root",
        default="third_party/pinchbench-skill",
        help=(
            "path to PinchBench skill repo root (contains tasks/ and assets/). "
            "Default: third_party/pinchbench-skill"
        ),
    )
    p_bench_pinch.add_argument(
        "--model",
        required=True,
        help="worker model id label (OpenClaw model id or pc-agent-loop backend label)",
    )
    p_bench_pinch.add_argument(
        "--adapter",
        choices=["openclaw", "pc-agent-loop"],
        default="openclaw",
        help="runtime adapter backend for benchmark execution",
    )
    p_bench_pinch.add_argument(
        "--spec",
        default="",
        help=(
            "optional governance spec file or directory for runtime execution "
            "(e.g. systems/institutions/egypt_pipeline)"
        ),
    )
    p_bench_pinch.add_argument(
        "--suite",
        default="all",
        help='task selection: "all", "automated-only", or comma-separated task IDs',
    )
    p_bench_pinch.add_argument(
        "--runs",
        type=int,
        default=1,
        help="number of runs per task",
    )
    p_bench_pinch.add_argument(
        "--worker-timeout",
        type=int,
        default=0,
        help=(
            "minimum worker timeout seconds for each stage dispatch. "
            "0 keeps spec/task defaults."
        ),
    )
    p_bench_pinch.add_argument(
        "--out-dir",
        default="traces/benchmarks/pinchbench",
        help="output directory for benchmark artifacts",
    )
    p_bench_pinch.add_argument(
        "--judge-model",
        default="",
        help="judge model id for llm_judge/hybrid tasks (default: same as --model)",
    )
    p_bench_pinch.add_argument(
        "--judge-timeout",
        type=int,
        default=180,
        help="judge timeout in seconds",
    )
    p_bench_pinch.add_argument(
        "--no-judge",
        action="store_true",
        help="skip llm judge for llm_judge/hybrid tasks",
    )
    p_bench_pinch.add_argument(
        "--keep-agents",
        action="store_true",
        help="do not delete temporary OpenClaw agents after run",
    )
    p_bench_pinch.add_argument(
        "--openclaw-bin",
        default="openclaw",
        help="OpenClaw executable path",
    )
    p_bench_pinch.add_argument(
        "--openclaw-deliver-mode",
        choices=["auto", "always", "never"],
        default="never",
        help="whether to append --deliver when invoking OpenClaw",
    )
    p_bench_pinch.add_argument(
        "--openclaw-project-dir",
        default="",
        help="working directory for OpenClaw CLI execution",
    )
    p_bench_pinch.add_argument(
        "--pc-agent-root",
        default="third_party/pc-agent-loop",
        help="path to pc-agent-loop root directory",
    )
    p_bench_pinch.add_argument(
        "--pc-mykey",
        default="",
        help="optional path to mykey.py/mykey.json for pc-agent-loop",
    )
    p_bench_pinch.add_argument(
        "--pc-llm-no",
        type=int,
        default=-1,
        help="select backend index in pc-agent-loop (default: keep runtime default)",
    )
    p_bench_pinch.add_argument(
        "--pc-shared-instance",
        action="store_true",
        help="share one pc-agent-loop agent instance for all runtime_ids",
    )

    args = parser.parse_args()
    logging.basicConfig(
        level=getattr(logging, str(args.log_level).upper(), logging.INFO),
        format="%(asctime)s [%(name)s] %(levelname)s %(message)s",
    )

    try:
        if args.cmd == "compile":
            return _cmd_compile(args.spec, args.out)
        if args.cmd == "validate":
            return _cmd_validate(args.spec)
        if args.cmd == "init-spec":
            return _cmd_init_spec(args)
        if args.cmd == "run":
            return _cmd_run(args)
        if args.cmd == "serve":
            return _cmd_serve(args)
        if args.cmd == "bench-pinch":
            return _cmd_bench_pinch(args)
    except SpecError as exc:
        print(f"[spec-error] {exc}", file=sys.stderr)
        raise SystemExit(2)
    except Exception as exc:
        print(f"[error] {exc}", file=sys.stderr)
        raise SystemExit(1)


def _cmd_compile(spec_path: str, out_path: str) -> None:
    spec = compile_spec(spec_path)
    ir = export_ir_json(spec)
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(ir, ensure_ascii=False, indent=2))
    print(f"compiled: {spec.meta.id} ({spec.meta.pattern}) -> {out}")


def _cmd_validate(spec_path: str) -> None:
    spec = compile_spec(spec_path)
    print(
        f"valid: id={spec.meta.id} pattern={spec.meta.pattern} "
        f"stages={len(spec.stages)} agents={len(spec.agents)}"
    )


def _cmd_init_spec(args: argparse.Namespace) -> None:
    spec = build_spec_template(
        spec_id=args.id,
        name=args.name.strip() or args.id,
        pattern=args.pattern,
    )
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(spec, ensure_ascii=False, indent=2))
    print(f"template-created: {out}")


def _cmd_run(args: argparse.Namespace) -> None:
    spec = compile_spec(args.spec)

    if args.adapter == "openclaw":
        adapter = OpenClawAdapter(
            executable=args.openclaw_bin,
            deliver_mode=args.openclaw_deliver_mode,
            project_dir=args.openclaw_project_dir.strip() or None,
        )
    elif args.adapter == "pc-agent-loop":
        adapter = PcAgentLoopAdapter(
            agent_root=args.pc_agent_root,
            shared_instance=args.pc_shared_instance,
            llm_no=(args.pc_llm_no if args.pc_llm_no >= 0 else None),
            mykey_path=args.pc_mykey.strip() or None,
        )
    else:
        scripted = {}
        if args.mock_script:
            scripted = json.loads(Path(args.mock_script).read_text())
        adapter = MockAdapter(scripted_decisions=scripted)

    store = JsonlStore(args.trace_out) if args.trace_out else None
    runtime = GovernanceRuntime(
        spec=spec,
        adapter=adapter,
        store=store,
        human_confirm_callback=_interactive_confirm if args.human_confirm else None,
    )

    task_id = args.task_id.strip() or f"TASK-{uuid.uuid4().hex[:8]}"
    state = runtime.run(
        task_id=task_id,
        title=args.title,
        input_text=args.input_text,
        max_steps=args.max_steps or None,
    )

    print(json.dumps(
        {
            "task_id": state.task_id,
            "status": state.status,
            "current_stage": state.current_stage,
            "steps": len(state.history),
            "history": [
                {
                    "idx": e.index,
                    "stage": e.stage_id,
                    "decision": e.decision,
                    "next": e.next_stage,
                    "summary": e.summary,
                }
                for e in state.history
            ],
            "shared_state": state.shared_state,
        },
        ensure_ascii=False,
        indent=2,
    ))


def _cmd_serve(args: argparse.Namespace) -> None:
    manager = TaskRunManager(
        trace_dir=args.trace_dir,
        institutions_path=args.institutions,
    )
    serve_dashboard(manager=manager, host=args.host, port=args.port)


def _cmd_bench_pinch(args: argparse.Namespace) -> None:
    config = PinchBenchRunConfig(
        pinch_root=Path(args.pinch_root),
        model=str(args.model).strip(),
        suite=str(args.suite).strip() or "all",
        runs=max(1, int(args.runs)),
        output_dir=Path(args.out_dir),
        adapter=str(args.adapter).strip() or "openclaw",
        openclaw_bin=str(args.openclaw_bin).strip() or "openclaw",
        openclaw_deliver_mode=str(args.openclaw_deliver_mode).strip() or "auto",
        openclaw_project_dir=(str(args.openclaw_project_dir).strip() or None),
        pc_agent_root=str(args.pc_agent_root).strip() or "third_party/pc-agent-loop",
        pc_mykey=(str(args.pc_mykey).strip() or None),
        pc_llm_no=(args.pc_llm_no if int(args.pc_llm_no) >= 0 else None),
        pc_shared_instance=bool(args.pc_shared_instance),
        worker_timeout_sec=max(0, int(args.worker_timeout)),
        judge_model=(str(args.judge_model).strip() or None),
        judge_timeout_sec=max(30, int(args.judge_timeout)),
        no_judge=bool(args.no_judge),
        keep_agents=bool(args.keep_agents),
        benchmark_spec_path=(Path(args.spec).expanduser() if str(args.spec).strip() else None),
    )
    out = run_pinchbench(config)
    print(json.dumps(out, ensure_ascii=False, indent=2))


def _interactive_confirm(**kwargs) -> bool:
    task = kwargs["task"]
    stage = kwargs["stage"]
    result = kwargs["result"]
    print("\n[HITL] Confirmation required")
    print(f"Task: {task.task_id} {task.title}")
    print(f"Stage: {stage.id}")
    print(f"Decision: {result.decision}")
    print(f"Summary: {result.summary}")
    ans = input("Approve? [y/N]: ").strip().lower()
    return ans in {"y", "yes"}


if __name__ == "__main__":
    main()
