"""CLI entrypoint for governance engine."""

from __future__ import annotations

import argparse
import json
import sys
import uuid
from pathlib import Path

from .adapters import MockAdapter, OpenClawAdapter
from .core.errors import SpecError
from .core.runtime import GovernanceRuntime
from .spec.compiler import compile_spec, export_ir_json
from .spec.templates import SUPPORTED_PATTERNS, build_spec_template
from .storage.jsonl import JsonlStore


def main() -> None:
    parser = argparse.ArgumentParser(description="MAS governance engine")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_compile = sub.add_parser("compile", help="compile CUE/JSON spec into normalized JSON IR")
    p_compile.add_argument("--spec", required=True, help="path to .cue or .json spec")
    p_compile.add_argument("--out", required=True, help="path to output JSON")

    p_validate = sub.add_parser("validate", help="validate spec")
    p_validate.add_argument("--spec", required=True, help="path to .cue or .json spec")

    p_init = sub.add_parser("init-spec", help="generate a starter spec template")
    p_init.add_argument("--id", required=True, help="spec id")
    p_init.add_argument("--name", default="", help="display name (default: same as id)")
    p_init.add_argument("--pattern", required=True, choices=SUPPORTED_PATTERNS)
    p_init.add_argument("--out", required=True, help="output JSON file path")

    p_run = sub.add_parser("run", help="execute a task with given governance spec")
    p_run.add_argument("--spec", required=True, help="path to .cue or .json spec")
    p_run.add_argument("--task-id", default="", help="task id (default autogenerated)")
    p_run.add_argument("--title", required=True, help="task title")
    p_run.add_argument("--input", required=True, dest="input_text", help="task input text")
    p_run.add_argument("--adapter", choices=["mock", "openclaw"], default="mock")
    p_run.add_argument("--mock-script", default="", help="JSON file: {agent_id: [decision,...]}")
    p_run.add_argument("--openclaw-bin", default="openclaw", help="OpenClaw executable path")
    p_run.add_argument(
        "--openclaw-deliver-mode",
        choices=["auto", "always", "never"],
        default="auto",
        help="whether to append --deliver when invoking OpenClaw",
    )
    p_run.add_argument(
        "--openclaw-project-dir",
        default="",
        help="working directory for OpenClaw CLI execution",
    )
    p_run.add_argument("--trace-out", default="", help="JSONL trace output path")
    p_run.add_argument("--max-steps", type=int, default=0, help="runtime step budget")
    p_run.add_argument("--human-confirm", action="store_true", help="enable interactive HITL callback")

    args = parser.parse_args()

    try:
        if args.cmd == "compile":
            return _cmd_compile(args.spec, args.out)
        if args.cmd == "validate":
            return _cmd_validate(args.spec)
        if args.cmd == "init-spec":
            return _cmd_init_spec(args)
        if args.cmd == "run":
            return _cmd_run(args)
    except SpecError as exc:
        print(f"[spec-error] {exc}", file=sys.stderr)
        raise SystemExit(2)
    except Exception as exc:
        print(f"[error] {exc}", file=sys.stderr)
        raise SystemExit(1)


def _cmd_compile(spec_path: str, out_path: str) -> None:
    spec = compile_spec(spec_path)
    ir = export_ir_json(spec)
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(ir, ensure_ascii=False, indent=2))
    print(f"compiled: {spec.meta.id} ({spec.meta.pattern}) -> {out}")


def _cmd_validate(spec_path: str) -> None:
    spec = compile_spec(spec_path)
    print(
        f"valid: id={spec.meta.id} pattern={spec.meta.pattern} "
        f"stages={len(spec.stages)} agents={len(spec.agents)}"
    )


def _cmd_init_spec(args: argparse.Namespace) -> None:
    spec = build_spec_template(
        spec_id=args.id,
        name=args.name.strip() or args.id,
        pattern=args.pattern,
    )
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(spec, ensure_ascii=False, indent=2))
    print(f"template-created: {out}")


def _cmd_run(args: argparse.Namespace) -> None:
    spec = compile_spec(args.spec)

    if args.adapter == "openclaw":
        adapter = OpenClawAdapter(
            executable=args.openclaw_bin,
            deliver_mode=args.openclaw_deliver_mode,
            project_dir=args.openclaw_project_dir.strip() or None,
        )
    else:
        scripted = {}
        if args.mock_script:
            scripted = json.loads(Path(args.mock_script).read_text())
        adapter = MockAdapter(scripted_decisions=scripted)

    store = JsonlStore(args.trace_out) if args.trace_out else None
    runtime = GovernanceRuntime(
        spec=spec,
        adapter=adapter,
        store=store,
        human_confirm_callback=_interactive_confirm if args.human_confirm else None,
    )

    task_id = args.task_id.strip() or f"TASK-{uuid.uuid4().hex[:8]}"
    state = runtime.run(
        task_id=task_id,
        title=args.title,
        input_text=args.input_text,
        max_steps=args.max_steps or None,
    )

    print(json.dumps(
        {
            "task_id": state.task_id,
            "status": state.status,
            "current_stage": state.current_stage,
            "steps": len(state.history),
            "history": [
                {
                    "idx": e.index,
                    "stage": e.stage_id,
                    "decision": e.decision,
                    "next": e.next_stage,
                    "summary": e.summary,
                }
                for e in state.history
            ],
            "shared_state": state.shared_state,
        },
        ensure_ascii=False,
        indent=2,
    ))


def _interactive_confirm(**kwargs) -> bool:
    task = kwargs["task"]
    stage = kwargs["stage"]
    result = kwargs["result"]
    print("\n[HITL] Confirmation required")
    print(f"Task: {task.task_id} {task.title}")
    print(f"Stage: {stage.id}")
    print(f"Decision: {result.decision}")
    print(f"Summary: {result.summary}")
    ans = input("Approve? [y/N]: ").strip().lower()
    return ans in {"y", "yes"}


if __name__ == "__main__":
    main()
